# frontend code deploy pipeline
name: HTML CI pipeline

on:
  push:
    paths:
      - "frontend"
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  HTML-pipeline:
    runs-on:  ubuntu-latest
    env:
      AWS_REGION: "ap-south-1"
    environment: apply-changes-html

    steps:
          -   name: Checkout Code
              uses: actions/checkout@v4

          -   name:   Configure AWS Credentials
              uses:   aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
              with:   
                role-to-assume: arn:aws:iam::495599765058:role/terraform-cicd-pipeline-automation-access
                aws-region: ${{ env.AWS_REGION }}

          - name: Push File to S3
            run: aws s3 sync frontend/ s3://<bucket_name>/destination-folder/
