# apply lints to the frontend/* folder 
name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/*"

permissions:
  contents: read

jobs:
  basic-frontend-ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend/**"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simple HTML Lint
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose "*.html"
