name: Frontend App CI

on:
  pull_request:
    paths:
      - "frontend/**"

  push:
    branches:
      - 'main'
    paths:
      - "frontend/**"

permissions:
  id-token: write
  contents: read

env:
  FRONTEND_WORKDIR: "frontend"
  AWS_REGION: "ap-south-1"

jobs:
  basic-frontend-ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{  env.FRONTEND_WORKDIR  }}

    # basic lint step
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simple HTML Lint
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose "*.html"

  deploy-code:
    runs-on:  ubuntu-latest
    needs:  basic-frontend-ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ${{  env.FRONTEND_WORKDIR  }}

    steps:
          -   name: Checkout Code
              uses: actions/checkout@v4

          -   name:   Configure AWS Credentials
              uses:   aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
              with:   
                role-to-assume: arn:aws:iam::495599765058:role/terraform-cicd-pipeline-automation-access
                aws-region: ${{ env.AWS_REGION }}

          - name: Push File to S3
            run: aws s3 sync frontend/ s3://<bucket_name>/destination-folder/
