# terraform deploy pipeline
on:
    push:
        branches:
          - main
        paths:
            -   'modules/**'
    pull_request:
        branches:
          - main
        paths:
            -   'modules/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "ap-south-1"
  TF_WORKING_DIR: "./modules"

jobs:
    validation:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory:  ${{ env.TF_WORKING_DIR  }}
        steps:
            -   name:   Checkout Code
                uses:   actions/checkout@v4

            -   name:   Setup Terraform CLI
                uses:   hashicorp/setup-terraform@v4

            -   name:   Run Terraform Init
                run:    terrform init -backend=false

            -   name:   Validate and Format Terraform Code
                run:    |
                        terraform validate
                        terraform fmt

            -   name:   Setup Tflint
                uses:   terraform-linters/setup-tflint@v6
                with:
                  cache:  true

            -   name:   Run Tflint
                run:    |
                        tflint --init
                        tflint

            -   name:   Run Terraform Tests
                run:    terraform test

    plan:
        runs-on:    ubuntu-latest
        needs:      validation
        defaults:
          run:
            working-directory: ${{  env.TF_WORKING_DIR  }}

        steps:
            -   name:   Checkout code
                uses:   action/checkout@v4

            -   name:   Checkout Terraform Code
                uses:   hashicorp/setup-terraform@v4

            -   name:   Configure AWS Credentials
                uses:   aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
                with:   
                    role-to-assume: arn:aws:iam::495599765058:role/terraform-cicd-pipeline-automation-access
                    aws-region: ${{ env.AWS_REGION }}

            -   name:   Init Terraform
                run:    terraform init

                # add the plan as a comment
            -   name:   Run Terraform Plan
                run:    terraform plan -out=tfplan -input=false

            # -   name: Add comment to Pull Request
            #     uses: actions/github-script@v7
            #     with:
            #         script: |
            #                 github.rest.issues.createComment({
            #                 issue_number: context.issue.number,
            #                 owner: context.repo.owner,
            #                 repo: context.repo.repo,
            #                 body: '${terraform plan -out=tfplan -input=false}'
            #                 })

            -   name:   Upload Plan Artifact
                uses:   actions/upload-artifact@v4
                with:
                    name:   tfplan
                    path:   ${{ env.TF_WORKING_DIR }}/tfplan
                    retention-days: 1

    apply_changes:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        defaults:
          run:
            working-directory: ${{  env.TF_WORKING_DIR  }}

        needs: plan
        environment: apply-changes

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name:   Configure AWS Credentials
              uses:   aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
              with:   
                role-to-assume: arn:aws:iam::495599765058:role/terraform-cicd-pipeline-automation-access
                aws-region: ${{ env.AWS_REGION }}

            -   name:   Init Terraform
                run: terraform init

            -   name:   Download Plan Artifact
                uses:   actions/download-artifact@v4
                with:
                    name:   tfplan
                    path:   'modules'

            -   name:   Terraform Apply
                run:    terraform apply -input=false tfplan
